language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
 
matrix:
  allow_failures:
    - php: 7.0

install:
  - composer install

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit


after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml